<?php
/**
 * Teal core class map.
 *
 * This file is automatically generated by the "build classmap" command under the "build" folder.
 * Do not modify it directly.
 *
 * @link http://teal.blue/
 *
 * @copyright Copyright (c) 2013 Teal Software
 * @license http://teal.blue/license
 * @author Jacob Morrison <jacob@tealcascade.com>
 */
defined('TEAL_CORE_PATH') or define('TEAL_CORE_PATH', dirname(__FILE__) . DIRECTORY_SEPARATOR . 'library');

return [
    'teal\Teal' => TEAL_CORE_PATH . '/Teal.php',
    'teal\base\Component' => TEAL_CORE_PATH . '/base/Component.php',
    'teal\base\Engine' => TEAL_CORE_PATH . '/base/Engine.php',
    'teal\base\Object' => TEAL_CORE_PATH . '/base/Object.php',
    'teal\base\exceptions\AccessException' => TEAL_CORE_PATH . '/base/exceptions/AccessException.php',
    'teal\base\exceptions\Exception' => TEAL_CORE_PATH . '/base/exceptions/Exception.php',
    'teal\base\exceptions\HttpException' => TEAL_CORE_PATH . '/base/exceptions/HttpException.php',
    'teal\base\language\Inflector' => TEAL_CORE_PATH . '/base/language/Inflector.php',
    'teal\base\language\Noun' => TEAL_CORE_PATH . '/base/language/Noun.php',
    'teal\base\language\Verb' => TEAL_CORE_PATH . '/base/language/Verb.php',
    'teal\base\language\Word' => TEAL_CORE_PATH . '/base/language/Word.php',
    'teal\db\ActiveRecord' => TEAL_CORE_PATH . '/db/ActiveRecord.php',
    'teal\db\Connection' => TEAL_CORE_PATH . '/db/Connection.php',
    'teal\db\behaviors\Access' => TEAL_CORE_PATH . '/db/behaviors/Access.php',
    'teal\db\behaviors\ActiveRecord' => TEAL_CORE_PATH . '/db/behaviors/ActiveRecord.php',
    'teal\db\behaviors\Blame' => TEAL_CORE_PATH . '/db/behaviors/Blame.php',
    'teal\db\behaviors\Date' => TEAL_CORE_PATH . '/db/behaviors/Date.php',
    'teal\db\behaviors\Registry' => TEAL_CORE_PATH . '/db/behaviors/Registry.php',
    'teal\db\behaviors\Relatable' => TEAL_CORE_PATH . '/db/behaviors/Relatable.php',
    'teal\db\behaviors\SearchTerm' => TEAL_CORE_PATH . '/db/behaviors/SearchTerm.php',
    'teal\db\models\Aca' => TEAL_CORE_PATH . '/db/models/Aca.php',
    'teal\db\models\Acl' => TEAL_CORE_PATH . '/db/models/Acl.php',
    'teal\db\models\AclRole' => TEAL_CORE_PATH . '/db/models/AclRole.php',
    'teal\db\models\Registry' => TEAL_CORE_PATH . '/db/models/Registry.php',
    'teal\db\models\Role' => TEAL_CORE_PATH . '/db/models/Role.php',
    'teal\helpers\Date' => TEAL_CORE_PATH . '/helpers/Date.php',
    'teal\helpers\FileStorage' => TEAL_CORE_PATH . '/helpers/FileStorage.php',
    'teal\helpers\Purifier' => TEAL_CORE_PATH . '/helpers/Purifier.php',
    'teal\helpers\Set' => TEAL_CORE_PATH . '/helpers/Set.php',
    'teal\security\Gatekeeper' => TEAL_CORE_PATH . '/security/Gatekeeper.php',
    'teal\security\identity\Identity' => TEAL_CORE_PATH . '/security/identity/Identity.php',
    'teal\security\identity\providers\LDAP' => TEAL_CORE_PATH . '/security/identity/providers/LDAP.php',
    'teal\security\identity\providers\Provider' => TEAL_CORE_PATH . '/security/identity/providers/Provider.php',
    'teal\security\role\Engine' => TEAL_CORE_PATH . '/security/role/Engine.php',
    'teal\security\role\Role' => TEAL_CORE_PATH . '/security/role/Role.php',
    'teal\setup\Exception' => TEAL_CORE_PATH . '/setup/Exception.php',
    'teal\setup\Migrator' => TEAL_CORE_PATH . '/setup/Migrator.php',
    'teal\setup\Setup' => TEAL_CORE_PATH . '/setup/Setup.php',
    'teal\setup\Task' => TEAL_CORE_PATH . '/setup/Task.php',
    'teal\web\Color' => TEAL_CORE_PATH . '/web/Color.php',
    'teal\web\Controller' => TEAL_CORE_PATH . '/web/Controller.php',
    'teal\web\DbSession' => TEAL_CORE_PATH . '/web/DbSession.php',
];
