<?php
/**
 * Infinite core class map.
 *
 * This file is automatically generated by the "build classmap" command under the "build" folder.
 * Do not modify it directly.
 *
 * @link http://www.infinitecascade.com/
 * @copyright Copyright (c) 2013 Infinite Cascade
 * @license http://www.infinitecascade.com/license
 * @author Jacob Morrison <jacob@infinitecascade.com>
 * @package infinite
 */


defined('INFINITE_CORE_PATH') or define('INFINITE_CORE_PATH', dirname(__FILE__) . DIRECTORY_SEPARATOR . 'library');
return [
	'infinite\Infinite' => INFINITE_CORE_PATH . '/Infinite.php',
	'infinite\base\Component' => INFINITE_CORE_PATH . '/base/Component.php',
	'infinite\base\Engine' => INFINITE_CORE_PATH . '/base/Engine.php',
	'infinite\base\Object' => INFINITE_CORE_PATH . '/base/Object.php',
	'infinite\base\exceptions\AccessException' => INFINITE_CORE_PATH . '/base/exceptions/AccessException.php',
	'infinite\base\exceptions\Exception' => INFINITE_CORE_PATH . '/base/exceptions/Exception.php',
	'infinite\base\exceptions\HttpException' => INFINITE_CORE_PATH . '/base/exceptions/HttpException.php',
	'infinite\base\language\Inflector' => INFINITE_CORE_PATH . '/base/language/Inflector.php',
	'infinite\base\language\Noun' => INFINITE_CORE_PATH . '/base/language/Noun.php',
	'infinite\base\language\Verb' => INFINITE_CORE_PATH . '/base/language/Verb.php',
	'infinite\base\language\Word' => INFINITE_CORE_PATH . '/base/language/Word.php',
	'infinite\db\ActiveRecord' => INFINITE_CORE_PATH . '/db/ActiveRecord.php',
	'infinite\db\Connection' => INFINITE_CORE_PATH . '/db/Connection.php',
	'infinite\db\behaviors\Access' => INFINITE_CORE_PATH . '/db/behaviors/Access.php',
	'infinite\db\behaviors\ActiveRecord' => INFINITE_CORE_PATH . '/db/behaviors/ActiveRecord.php',
	'infinite\db\behaviors\Blame' => INFINITE_CORE_PATH . '/db/behaviors/Blame.php',
	'infinite\db\behaviors\Date' => INFINITE_CORE_PATH . '/db/behaviors/Date.php',
	'infinite\db\behaviors\Registry' => INFINITE_CORE_PATH . '/db/behaviors/Registry.php',
	'infinite\db\behaviors\Relatable' => INFINITE_CORE_PATH . '/db/behaviors/Relatable.php',
	'infinite\db\behaviors\SearchTerm' => INFINITE_CORE_PATH . '/db/behaviors/SearchTerm.php',
	'infinite\db\models\Aca' => INFINITE_CORE_PATH . '/db/models/Aca.php',
	'infinite\db\models\Acl' => INFINITE_CORE_PATH . '/db/models/Acl.php',
	'infinite\db\models\AclRole' => INFINITE_CORE_PATH . '/db/models/AclRole.php',
	'infinite\db\models\Registry' => INFINITE_CORE_PATH . '/db/models/Registry.php',
	'infinite\db\models\Role' => INFINITE_CORE_PATH . '/db/models/Role.php',
	'infinite\helpers\Date' => INFINITE_CORE_PATH . '/helpers/Date.php',
	'infinite\helpers\FileStorage' => INFINITE_CORE_PATH . '/helpers/FileStorage.php',
	'infinite\helpers\Purifier' => INFINITE_CORE_PATH . '/helpers/Purifier.php',
	'infinite\helpers\Set' => INFINITE_CORE_PATH . '/helpers/Set.php',
	'infinite\security\Gatekeeper' => INFINITE_CORE_PATH . '/security/Gatekeeper.php',
	'infinite\security\identity\Identity' => INFINITE_CORE_PATH . '/security/identity/Identity.php',
	'infinite\security\identity\providers\LDAP' => INFINITE_CORE_PATH . '/security/identity/providers/LDAP.php',
	'infinite\security\identity\providers\Provider' => INFINITE_CORE_PATH . '/security/identity/providers/Provider.php',
	'infinite\security\role\Engine' => INFINITE_CORE_PATH . '/security/role/Engine.php',
	'infinite\security\role\Role' => INFINITE_CORE_PATH . '/security/role/Role.php',
	'infinite\setup\Exception' => INFINITE_CORE_PATH . '/setup/Exception.php',
	'infinite\setup\Migrator' => INFINITE_CORE_PATH . '/setup/Migrator.php',
	'infinite\setup\Setup' => INFINITE_CORE_PATH . '/setup/Setup.php',
	'infinite\setup\Task' => INFINITE_CORE_PATH . '/setup/Task.php',
	'infinite\web\Color' => INFINITE_CORE_PATH . '/web/Color.php',
	'infinite\web\Controller' => INFINITE_CORE_PATH . '/web/Controller.php',
	'infinite\web\DbSession' => INFINITE_CORE_PATH . '/web/DbSession.php',
];
